"""Backend package for SignalDesk."""

from signaldesk_backend.config import Settings
from signaldesk_backend.indicators import (
    MacdResult,
    average_true_range,
    exponential_moving_average,
    macd,
    relative_strength_index,
    relative_volume,
    simple_moving_average,
    volume_moving_average,
)
from signaldesk_backend.models import (
    Candle,
    KeyLevels,
    Provenance,
    ProviderCapability,
    ProviderResult,
    Quote,
    SignalCard,
    Symbol,
    TechnicalEvent,
    TechnicalSnapshot,
)
from signaldesk_backend.providers import (
    FallbackProvider,
    FmpProvider,
    LocalCsvProvider,
    LocalFixtureProvider,
    MarketDataProvider,
    PlaceholderEnhancedProvider,
    PolygonProvider,
    ProviderRegistry,
    StooqProvider,
    TwelveDataProvider,
    YFinanceProvider,
    default_provider_registry,
    fallback_provider_call,
    normalize_provider_name,
    provider_rate_limit_failure,
    redact_provider_diagnostic,
)

__all__ = [
    "Candle",
    "FallbackProvider",
    "FmpProvider",
    "KeyLevels",
    "LocalCsvProvider",
    "LocalFixtureProvider",
    "MacdResult",
    "MarketDataProvider",
    "PlaceholderEnhancedProvider",
    "PolygonProvider",
    "ProviderCapability",
    "ProviderRegistry",
    "ProviderResult",
    "Provenance",
    "Quote",
    "Settings",
    "SignalCard",
    "StooqProvider",
    "Symbol",
    "TechnicalEvent",
    "TechnicalSnapshot",
    "TwelveDataProvider",
    "YFinanceProvider",
    "average_true_range",
    "default_provider_registry",
    "exponential_moving_average",
    "fallback_provider_call",
    "macd",
    "normalize_provider_name",
    "provider_rate_limit_failure",
    "redact_provider_diagnostic",
    "relative_strength_index",
    "relative_volume",
    "simple_moving_average",
    "volume_moving_average",
]
